# Generated by Django 4.0 on 2022-12-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('value', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('client', models.CharField(max_length=128)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_type', models.CharField(default='cc', max_length=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_product.product')),
            ],
        ),
    ]
